#pragma once

#define VERDANT_DEVICE_ID "ESP32_1"
#define VERDANT_WIFI_SSID ""
#define VERDANT_WIFI_PASSWORD ""
#define VERDANT_MQTT_HOST ""
#define VERDANT_MQTT_PORT 8883
#define VERDANT_MQTT_USERNAME ""
#define VERDANT_MQTT_PASSWORD ""
#define VERDANT_WEATHER_API_KEY ""
#define VERDANT_WEATHER_LATITUDE ""
#define VERDANT_WEATHER_LONGITUDE ""
#define VERDANT_TELEGRAM_BOT_TOKEN ""
#define VERDANT_TELEGRAM_CHAT_ID ""
#define VERDANT_OTA_PASSWORD ""
#define VERDANT_SERVER_URL ""
